apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "hyofOYdM0YUBeTl8pXa+34HagI89oLfPxCn8pF98y6HxM2DDDbCemg+gePrvhIO+\nWpH5/n86QD1g6DZO65Uv+L5syro1k19w5Bz/cjq/+R1i6T8zUZMqfrGjI0eiWjRp\nwykxi6Bx603sIkKTR6smQ1JzlZ9H5eks2r8Ub4Do1TI="
