apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "mwgxhfroW/DeI+cF+hcUoVhcrUB55N72micKSyENPuWsFY+dVmDtMX/gyah9D/wv\nmoEmGcz2CWb4gv63TwaA8dv2lAXBifTCQNlxEKC6pbOBV91gSvJ0ytHchf6ao5Pf\nmsjTzW0cDl3VwV+Ct/gk57/j4KBZ8ukLJ3zNGn+BIEQ="
